[package]
name = "yew-tincture"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
yew = {git="https://github.com/DenisKolodin/yew", rev="150e5afd4cd1df5a267c087c6bc9e374a9a9031e"}
