[package]
name = "yew-tincture"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
yew = "0.17"
uuid = { version = "0.8", features = ["v4","wasm-bindgen"] }
